name: Build

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - run: git fetch --tags origin --force

      - name: Use Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: 'Build Artifact: Google Chrome extension'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Google Chrome extension
          path: dist/googlechrome/javadoc_search_frame_*.zip
          if-no-files-found: error

      - name: 'Build Artifact: Userscript'
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Userscript
          path: dist/userscript/javadoc_search_frame_*.user.js
          if-no-files-found: error
