name: Build

on: push

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: true

      - run: git fetch --tags origin --force

      - name: Use Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: 'Build Artifact: Google Chrome extension'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Google Chrome extension
          path: dist/googlechrome/javadoc_search_frame_*.zip
          if-no-files-found: error

      - name: 'Build Artifact: Userscript'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Userscript
          path: dist/userscript/javadoc_search_frame_*.user.js
          if-no-files-found: error
