name: Build

on:
  push:
    branches: ['**']
    tags: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Dependency Review
        uses: actions/dependency-review-action@v2.5.1
        if: github.event_name == 'pull_request'

      - name: Use Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 18.x
          cache: 'npm'

      - run: npm ci

      - run: npm run build

      - name: 'Build Artifact: Google Chrome extension'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Google Chrome extension
          path: dist/googlechrome/javadoc_search_frame_*.zip
          if-no-files-found: error

      - name: 'Build Artifact: Userscript'
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Userscript
          path: dist/userscript/javadoc_search_frame_*.user.js
          if-no-files-found: error
